### ISSUE TITLE
Enable and disable

### ISSUE THREAD

**Issue by Bobobaal** [gorbb/QwickTree#1]
I'm using the qwicktree plugin but when I put allowelftoggle on true and add the qwicktree.toggle.self perm to the perm list it says I don't have permission to use it.
http://prntscr.com/94zan3
http://prntscr.com/94zb1n
I added the useperms on the second printscreen if you may ask if I enabled that.

**Comment by gorbb** [comment]
Hey. Thanks for letting me know about this.

I've fixed the apparent cause of the issue, and will upload the new build soon.
