### ISSUE TITLE
Cant cut down dark oak or acacia 

### ISSUE THREAD

**Issue by Jemas328975** [gorbb/QwickTree#3]
seems to be a issue I have been having lately seems to be only the new trees with the issue ... could be something idn ... but if you can get back to me asap that would be great 

Jemas328975

**Comment by gorbb** [comment]
Hello,

There are no issues with new trees not chopping that I'm aware of. Could you please attach a copy of your server startup log and your config. If you use `/qt debug` to enable the debugger and then try to chop down the tree, could you also attach the results that gives out?

Thanks.

**Comment by gorbb** [comment]
Since there has been no response, I'm closing this issue. If you come across the problem again or gather the data required ([see troubleshooting](http://dev.bukkit.org/bukkit-plugins/qwicktree/pages/troubleshooting/)), please reopen this ticket, or create a new one
