### ISSUE TITLE
Add WorldGuard support

### ISSUE THREAD

**Issue by vitaly-rudenko** [gorbb/QwickTree#6]
Hi! Your plugin is awesome!
But can you, please, add the WorldGuard support?
People can break trees in regions, and it's a big problem.

Thank you! Hope you fix it soon.

**Comment by vitaly-rudenko** [comment]
Oh, I saw you wrote "QwickTree already has WorldGuard support", but it doesn't work, or I did something wrong.

Well, here is my config:
http://pastebin.com/veZu12j6

List of my plugins:

> Plugins (77): KeepItems, SmokeTrail, zPermissions, MobEggSpawnerBlocker, CustomRecipes, BanManager, SpectatorDisabler, UsefulAliases, CommandSync, LightAPI, CoreProtect, AsyncWorldEditInjector, dynmap, WorldEdit, OpenInv, Essentials, ClearLag, ChatControl, CreativeAddons, Chairs, ChatFreedom, ProtocolLib, Multiverse-Core, PowerlessLamps, AutoSaveWorld, LibsDisguises, weeTrade, AsyncWorldEdit, RedstoneClockDetector, EnchantPlus, EssentialsChat, NoFlyPvp, QwickTree, RandomBox, Vault, BungeeSlide, ShareControl, SimpleRename, PerWorldInventory, HolographicDisplays, WorldGuard, ItemStay, ChestCommands, EssentialsProtect, EssentialsGeoIP, DeathLogger, EssentialsSpawn, boosCooldowns, FastCraft, MarriageMaster, Jobs, CommandSign, Citizens, AncientGates, WGExtender, PillarShot, WorldeditRegions, ChestShop, PlaceholderAPI, NoFlyZone, AuthMe, PlaceholderInjector, BungeeTabListPlus, AutoCommandsPlus, TitleManager, CompatNoCheatPlus, InfoBoardReborn, NoCheatPlus, AuthMeBridge, Lift, AsyncWorldEdit-TitleManager, PlayerHeads, Skript, SkQuery, PirateSK, DrugMeUp, ShinyItems

(Yeah, too much, but everything works fine)

When i break a tree, WorldGuard says "Hey! You can't break blocks here!", but blocks are still dropping.

**Comment by gorbb** [comment]
Hi,

Could you please follow the [troubleshooting](http://dev.bukkit.org/bukkit-plugins/qwicktree/pages/troubleshooting/) steps for me, to check where exactly the issue is?

That page also details the information I'll require to be able to fully look into and resolve the issue. Please check that and then get back to me.

Thanks.

**Comment by vitaly-rudenko** [comment]
Sorry, I can't do it now. I have already fixed the plugin by myself.

Just add this into your listener:

```
LocalPlayer localPlayer = WGBukkit.getPlugin().wrapPlayer(player);
ApplicableRegionSet regions = WGBukkit.getRegionManager(block.getWorld()).getApplicableRegions(block.getLocation());

for (ProtectedRegion region : regions) {
    if(!region.isOwner(localPlayer) && !region.isMember(localPlayer)) {
        return;
    }
}
```

P.S. I've set WorldGuard dependency as NOT soft (depend: [WorldGuard, WorldEdit]), but you can do it and make a check in the code.

**Comment by gorbb** [comment]
Thanks for getting back to me. I'll assume you're using the latest version of Spigot, WorldEdit & WorldGuard.

As far as I can tell, the issue is with more than just WorldGuard, there's problems with other protection plugins too. I expect it's probably an easy fix so I'll investigate.

**Comment by vitaly-rudenko** [comment]
I'm using not the last build of  @<everything>, but the stablest.
I think problem can be anywhere, so, if you just add this simple check, every problem shoud be fixed.

Spigot version:

> This server is running CraftBukkit version git-Spigot-6abac0c-9935adc (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
> Checking version, please wait...
> You are 37 version(s) behind

WG: 6.1.1 SNAPSHOT.
WE: 6.1.1 SNAPSHOT.

If I have time, I'll send you troubleshooting steps.
